### ISSUE TITLE
希望增加长按保存图片功能

### ISSUE THREAD

**Issue by fangshengfy** [lanzhu1993/flutter_nineold#1]

**Comment by fangshengfy** [comment]
或者能增加回调函数

**Comment by lanzhu1993** [comment]
> 或者能增加回调函数

好的，还有什么需求吗？长按回掉事件

**Comment by fangshengfy** [comment]
> > 或者能增加回调函数
> 
> 好的，还有什么需求吗？长按回掉事件

希望能提供自定义超出9副图片以后的那个+n的文字样式

**Comment by fangshengfy** [comment]
蒙版的颜色最好也能自定义

**Comment by lanzhu1993** [comment]
> 蒙版的颜色最好也能自定义

好的，这个周会出新版本，

**Comment by lanzhu1993** [comment]
> 蒙版的颜色最好也能自定义

代码已经更新，今天可以更新版本了，ISSUE我关闭了
