### ISSUE TITLE
'dart:ui/painting.dart': Failed assertion: line 1194: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by fangshengfy** [lanzhu1993/flutter_nineold#2]
更新到1.03出现的问题，所有用到九宫格的图片都出现了错位的现象，无法正常使用
顺便长按事件希望能增加个参数，能获得当前图片的顺序或者直接返回图片,拿不到当前显示的图片的话长按事件就没什么用了

**Comment by fangshengfy** [comment]
> 更新到1.03出现的问题，所有用到九宫格的图片都出现了错位的现象，无法正常使用
> 顺便长按事件希望能增加个参数，能获得当前图片的顺序或者直接返回图片

**Comment by fangshengfy** [comment]
原因好像是现在版本自定义样式变成必填项了？希望用@required标注下必填项

**Comment by lanzhu1993** [comment]
> 原因好像是现在版本自定义样式变成必填项了？希望用@required标注下必填项

好的，我近期会修复一下

**Comment by lanzhu1993** [comment]
> 更新到1.03出现的问题，所有用到九宫格的图片都出现了错位的现象，无法正常使用
> 顺便长按事件希望能增加个参数，能获得当前图片的顺序或者直接返回图片,拿不到当前显示的图片的话长按事件就没什么用了

问题已经修复，发布1.3.1版本了
