### ISSUE TITLE
相同图片url会导致hero的tag重复

### ISSUE THREAD

**Issue by fangshengfy** [lanzhu1993/flutter_nineold#3]
现在组件是直接拿图片地址作为hero的tag,但如果使用TabBarView同时引用了一张图片就会导致异常

**Comment by fangshengfy** [comment]
希望tag能复杂一点

**Comment by fangshengfy** [comment]
There are multiple heroes that share the same tag within a subtree.
这是异常信息

**Comment by lanzhu1993** [comment]
> There are multiple heroes that share the same tag within a subtree.
> 这是异常信息

我测试出来这个问题了，目前在想好的方案来解决Hero Tag重复问题，目前采用的Tag标记是图片地址+ index 偏移量的方案，这个周末修复一下，谢谢你一直提出来的建议

**Comment by lanzhu1993** [comment]
> > There are multiple heroes that share the same tag within a subtree.
> > 这是异常信息
> 
> 我测试出来这个问题了，目前在想好的方案来解决Hero Tag重复问题，目前采用的Tag标记是图片地址+ index 偏移量的方案，这个周末修复一下，谢谢你一直提出来的建议

该问题已经修复，前面段时间一直在找工作

**Comment by fangshengfy** [comment]
1.3.2没有上传flutter pub,更新不了啊

**Comment by fangshengfy** [comment]
> > > There are multiple heroes that share the same tag within a subtree.
> > > 这是异常信息
> > 
> > 
> > 我测试出来这个问题了，目前在想好的方案来解决Hero Tag重复问题，目前采用的Tag标记是图片地址+ index 偏移量的方案，这个周末修复一下，谢谢你一直提出来的建议
> 
> 该问题已经修复，前面段时间一直在找工作

希望更新下

**Comment by lanzhu1993** [comment]
> > > > There are multiple heroes that share the same tag within a subtree.
> > > > 这是异常信息
> > > 
> > > 
> > > 我测试出来这个问题了，目前在想好的方案来解决Hero Tag重复问题，目前采用的Tag标记是图片地址+ index 偏移量的方案，这个周末修复一下，谢谢你一直提出来的建议
> > 
> > 
> > 该问题已经修复，前面段时间一直在找工作
> 
> 希望更新下

不好意思，最近由于网络原因，我开了梯子也发布不上去，在找好的梯子，

**Comment by lanzhu1993** [comment]
> 1.3.2没有上传flutter pub,更新不了啊

目前已经更新Version 1.3.2版本了，可以继续使用了，前面一段时间有点忙，忘记推包了
