### ISSUE TITLE
点击图片画廊图片黑的，不显示

### ISSUE THREAD

**Issue by hlovingness** [lanzhu1993/flutter_nineold#4]

**Comment by lanzhu1993** [comment]
> No description provided.
请问图片地址正确吗？图片是黑色的网址加载不出来，请提供图片地址，谢谢

**Comment by hlovingness** [comment]
> > 请问图片地址正确吗？图片是黑色的网址加载不出来，请提供图片地址，谢谢

列表图正常显示

**Comment by lanzhu1993** [comment]
> > > 请问图片地址正确吗？图片是黑色的网址加载不出来，请提供图片地址，谢谢
> 
> 列表图正常显示
目前问题已经修复，前面段时间一直在找工作
