### ISSUE TITLE
单击九宫格图片浏览大图，crash

### ISSUE THREAD

**Issue by dengbin9009** [lanzhu1993/flutter_nineold#6]
点击后定位在这
![image](https://user-images.githubusercontent.com/3061194/93567157-cc9b7a80-f9c0-11ea-8b4a-4bb28cf8ebe5.png)

报错
```

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.
```

**Comment by lanzhu1993** [comment]
> 点击后定位在这
> ![image](https://user-images.githubusercontent.com/3061194/93567157-cc9b7a80-f9c0-11ea-8b4a-4bb28cf8ebe5.png)
> 
> 报错
> 
> ```
> 
> ════════ Exception caught by scheduler library ═════════════════════════════════
> The following assertion was thrown during a scheduler callback:
> There are multiple heroes that share the same tag within a subtree.
> ```
你列表图片的地址链接有重复的吗？我前面在考虑是否去掉hero动画

**Comment by lanzhu1993** [comment]
> 点击后定位在这
> ![image](https://user-images.githubusercontent.com/3061194/93567157-cc9b7a80-f9c0-11ea-8b4a-4bb28cf8ebe5.png)
> 
> 报错
> 
> ```
> 
> ════════ Exception caught by scheduler library ═════════════════════════════════
> The following assertion was thrown during a scheduler callback:
> There are multiple heroes that share the same tag within a subtree.
> ```

问题已经修复，已经发布1.3.3.引入uuid库，使图片的hero 动画tag 唯一了

**Comment by dengbin9009** [comment]
同样的问题还是存在，我的图片里面里面没有相同的链接

**Comment by lanzhu1993** [comment]
> 同样的问题还是存在，我的图片里面里面没有相同的链接
方便贴出你的代码吗？报错原因是因为重复定义相同的hero,1.3.3版本修复了优化了

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

**Comment by lanzhu1993** [comment]
> 同样的问题还是存在，我的图片里面里面没有相同的链接

方便贴出你的代码吗？报错原因是因为重复定义相同的hero,1.3.3版本修复了优化了
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

**Comment by dengbin9009** [comment]
![image](https://user-images.githubusercontent.com/3061194/93729586-c511e680-fbf7-11ea-9bed-1f510174b6e4.png)
![image](https://user-images.githubusercontent.com/3061194/93729607-da871080-fbf7-11ea-9322-6c8699d9f3bd.png)
![image](https://user-images.githubusercontent.com/3061194/93729643-fd192980-fbf7-11ea-970f-b8159369d467.png)
![image](https://user-images.githubusercontent.com/3061194/93729675-1b7f2500-fbf8-11ea-8d4c-b9e6caf1da5e.png)
![image](https://user-images.githubusercontent.com/3061194/93729630-f094d100-fbf7-11ea-96bc-98babecae092.png)


每张图片都是不一样的

**Comment by dengbin9009** [comment]
前面有些警告
![image](https://user-images.githubusercontent.com/3061194/93730348-c5f84780-fbfa-11ea-9628-e1a0a56dddff.png)
![image](https://user-images.githubusercontent.com/3061194/93730712-6733cd80-fbfc-11ea-9698-f8489477989d.png)


但最后crash报错还是同样的
![image](https://user-images.githubusercontent.com/3061194/93730693-53886700-fbfc-11ea-96bd-0e184c77d2b0.png)

**Comment by lanzhu1993** [comment]
> ![image](https://user-images.githubusercontent.com/3061194/93729586-c511e680-fbf7-11ea-9bed-1f510174b6e4.png)
> ![image](https://user-images.githubusercontent.com/3061194/93729607-da871080-fbf7-11ea-9322-6c8699d9f3bd.png)
> ![image](https://user-images.githubusercontent.com/3061194/93729643-fd192980-fbf7-11ea-970f-b8159369d467.png)
> ![image](https://user-images.githubusercontent.com/3061194/93729675-1b7f2500-fbf8-11ea-8d4c-b9e6caf1da5e.png)
> ![image](https://user-images.githubusercontent.com/3061194/93729630-f094d100-fbf7-11ea-96bc-98babecae092.png)
> 
> 每张图片都是不一样的

方便加我QQ：1113799552，你代码有问题，我这边测试通过的，你能把图片显示相关的代码全部拷贝贴出来吗？我这边测试一下，不要截图啊，信息不全我很难定位

**Comment by dengbin9009** [comment]
你的qq要验证，俺不知道你的外号啊

**Comment by dengbin9009** [comment]
> 你的qq要验证，俺不知道你的外号啊

我的QQ：504656807

**Comment by lanzhu1993** [comment]
> 504656807

1.3.4版本已经更新了
