### ISSUE TITLE
listView中使用的场景，某一个cell下需要展示9张图时，出现crash

### ISSUE THREAD

**Issue by AcYangle** [lanzhu1993/flutter_nineold#7]
**Describe the bug**
listView中某一个cell下需要加载9张网络图片时，出现crash

**To Reproduce**
在listView中将有9张图的cell滑出时，经测试，只有iOS会出现此情况，安卓不会

**Comment by AcYangle** [comment]
另外，希望能够支持本地缓存策略

**Comment by lanzhu1993** [comment]
> 另外，希望能够支持本地缓存策略

谢谢你的建议，我尽快修复，由于现在pub发布不上去，代码我会更新的

**Comment by AcYangle** [comment]
我是使用的下载包的方式集成的，并且将加载图片部分修改为：
return Stack(
      fit: StackFit.expand,
      alignment: Alignment.center,
      children: <Widget>[
        // Container(
        //   color: Colors.grey,
        //   child: Center(
        //     child: SizedBox(
        //       width: loaderSize,
        //       height: loaderSize,
        //       child: _buildCircularProgressIndicator(
        //           cpBackgroundColor: backgroundColor,
        //           cpStrokeWidth: strokeWidth,
        //           cpValueColor: valueColor),
        //     ),
        //   ),
        // ),
        // FadeInImage.memoryNetwork(
        //   image: url,
        //   fit: fit,
        //   placeholder: kTransparentImage,
        // ),
        CachedNetworkImage(
          imageUrl: url,
          imageBuilder: (context, imageProvider) => Container(
            decoration: BoxDecoration(
              color: Colors.transparent,
              borderRadius: BorderRadius.all(Radius.circular(4)),
              image: DecorationImage(
                image: imageProvider,
                fit: fit,
              ),
            ),
          ),
          placeholder: (context, url) => Container(
            color: Colors.grey,
            child: Center(
              child: SizedBox(
                width: loaderSize,
                height: loaderSize,
                child: _buildCircularProgressIndicator(
                    cpBackgroundColor: backgroundColor,
                    cpStrokeWidth: strokeWidth,
                    cpValueColor: valueColor),
              ),
            ),
          ),
          errorWidget: (context, url, error) => Icon(Icons.error),
        ),
      ],
    );
此处我也尝试还原为你的代码做过测试，同样会出现描述的问题

**Comment by AcYangle** [comment]
![image](https://user-images.githubusercontent.com/15205440/105001811-4c1e8080-5a6b-11eb-80ed-1a7a9a83d23d.png)

**Comment by lanzhu1993** [comment]
> **Describe the bug**
> listView中某一个cell下需要加载9张网络图片时，出现crash
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 在listView中将有9张图的cell滑出时，经测试，只有iOS会出现此情况，安卓不会

可以贴出你的错误信息吗？我本机在IOS调试上没有出现任何问题

**Comment by lanzhu1993** [comment]
> 我是使用的下载包的方式集成的，并且将加载图片部分修改为：
> return Stack(
> fit: StackFit.expand,
> alignment: Alignment.center,
> children: [
> // Container(
> // color: Colors.grey,
> // child: Center(
> // child: SizedBox(
> // width: loaderSize,
> // height: loaderSize,
> // child: _buildCircularProgressIndicator(
> // cpBackgroundColor: backgroundColor,
> // cpStrokeWidth: strokeWidth,
> // cpValueColor: valueColor),
> // ),
> // ),
> // ),
> // FadeInImage.memoryNetwork(
> // image: url,
> // fit: fit,
> // placeholder: kTransparentImage,
> // ),
> CachedNetworkImage(
> imageUrl: url,
> imageBuilder: (context, imageProvider) => Container(
> decoration: BoxDecoration(
> color: Colors.transparent,
> borderRadius: BorderRadius.all(Radius.circular(4)),
> image: DecorationImage(
> image: imageProvider,
> fit: fit,
> ),
> ),
> ),
> placeholder: (context, url) => Container(
> color: Colors.grey,
> child: Center(
> child: SizedBox(
> width: loaderSize,
> height: loaderSize,
> child: _buildCircularProgressIndicator(
> cpBackgroundColor: backgroundColor,
> cpStrokeWidth: strokeWidth,
> cpValueColor: valueColor),
> ),
> ),
> ),
> errorWidget: (context, url, error) => Icon(Icons.error),
> ),
> ],
> );
> 此处我也尝试还原为你的代码做过测试，同样会出现描述的问题

请参考DEMO，列表滑动在IOS以及Android测试都正常，同属图片缓存本身自带用的cached_network_image

**Comment by AcYangle** [comment]
直接就闪退了，没能收集到报错信息

**Comment by lanzhu1993** [comment]
> 直接就闪退了，没能收集到报错信息

使用项目集成参考我的另外一个项目`https://github.com/GZFlutterInc/flutter_yuwan_clone`

**Comment by AcYangle** [comment]
![image](https://user-images.githubusercontent.com/15205440/105332560-b839e980-5c0f-11eb-9e67-bba1f40b3a6d.png)
这是我一个cell里的布局，注释掉NineOldWidget的使用，测试就不会出现闪退的问题

**Comment by AcYangle** [comment]
截图上使用的，我是用pub集成的1.3.3版本验证的

**Comment by AcYangle** [comment]
我大概知道问题了，我的动态列表里面没做封面图逻辑，每张图都有好几百kb，甚至1mb以上的，你的demo里面的图，几乎都是小于100kb的，加载比我这个情况要快很多，我这边因为图片大，加载时间长，ListView滑动快的话，就会创建非常多的子线程去异步加载图片，我推测是因为这个原因造成内存溢出，导致闪退

**Comment by lanzhu1993** [comment]
> 我大概知道问题了，我的动态列表里面没做封面图逻辑，每张图都有好几百kb，甚至1mb以上的，你的demo里面的图，几乎都是小于100kb的，加载比我这个情况要快很多，我这边因为图片大，加载时间长，ListView滑动快的话，就会创建非常多的子线程去异步加载图片，我推测是因为这个原因造成内存溢出，导致闪退

1.3.4版本已经pub pushlish 了，可官网依赖
