### ISSUE TITLE
升级下photo_view 插件吧

### ISSUE THREAD

**Issue by 1227228155** [lanzhu1993/flutter_nineold#8]
Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/E:/flutter2.5.0/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/E:/flutter2.5.0/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);

**Comment by lanzhu1993** [comment]
好的，好久没上了，我把所有插件都更新一下

**Comment by lanzhu1993** [comment]
> Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
> 
> * 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/E:/flutter2.5.0/packages/flutter/lib/src/gestures/events.dart').
> * 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/E:/flutter2.5.0/packages/flutter/lib/src/gestures/events.dart').
>   super.addAllowedPointer(event);

好的，好久没上了，我把所有插件都更新一下

**Comment by lanzhu1993** [comment]
> Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
> 
> * 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/E:/flutter2.5.0/packages/flutter/lib/src/gestures/events.dart').
> * 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/E:/flutter2.5.0/packages/flutter/lib/src/gestures/events.dart').
>   super.addAllowedPointer(event);
已经升级了，你更新pub版本
