### ISSUE TITLE
flutter 2.10 版本  不兼容

### ISSUE THREAD

**Issue by 1227228155** [lanzhu1993/flutter_nineold#9]
Flutter 2.10 强制要求 Kotlin 1.5.31 以上的版本

**Comment by lanzhu1993** [comment]
最近一直在出差，后面我会更新的

**Comment by lanzhu1993** [comment]
> Flutter 2.10 强制要求 Kotlin 1.5.31 以上的版本

最近一直在出差，后面我会更新的

**Comment by lanzhu1993** [comment]
> Flutter 2.10 强制要求 Kotlin 1.5.31 以上的版本

3.2.0已经发布，升级flutter到2.10。并且更新pub依赖库版本
